export const expenses = [
  {
    _id: 1,
    description: 'Uber',
    price: '7,00',
    category: 'Transporte',
    priority: 'Alta',
    iconUrl: '../static/img/icons/icon-car-outline.svg',
  }, {
    _id: 2,
    description: 'Churrasco',
    price: '100,00',
    category: 'Lazer',
    priority: 'Alta',
    iconUrl: '../static/img/icons/icon-recreation-outline.svg',
  }, {
    _id: 3,
    description: 'Maçã',
    price: '7,00',
    category: 'Alimentação',
    priority: 'Alta',
    iconUrl: '../static/img/icons/icon-burger-outline.svg',
  }, {
    _id: 4,
    description: 'Pizzaria',
    price: '67,80',
    category: 'Alimentação',
    priority: 'Alta',
    iconUrl: '../static/img/icons/icon-burger-outline.svg',
  }, {
    _id: 5,
    description: 'Vestido',
    price: '210,00',
    category: 'Vestimenta',
    priority: 'Alta',
    iconUrl: '../static/img/icons/icon-shirt-outline.svg',
  }, {
    _id: 6,
    description: 'Uber',
    price: '6,50',
    category: 'Transporte',
    priority: 'Alta',
    iconUrl: '../static/img/icons/icon-car-outline.svg',
  }, {
    _id: 7,
    description: 'Cinema',
    price: '22,00',
    category: 'Lazer',
    priority: 'Alta',
    iconUrl: '../static/img/icons/icon-recreation-outline.svg',
  }, {
    _id: 8,
    description: 'Consulta Psico',
    price: '150,00',
    category: 'Saúde',
    priority: 'Alta',
    iconUrl: '../static/img/icons/icon-heart-outline.svg',
  }, {
    _id: 9,
    description: 'Hamburgueria',
    price: '107,40',
    category: 'Alimentação',
    priority: 'Alta',
    iconUrl: '../static/img/icons/icon-burger-outline.svg',
  }, {
    _id: 10,
    description: 'Curso Udemy Python',
    price: '70,00',
    category: 'Estudo',
    priority: 'Alta',
    iconUrl: '../static/img/icons/icon-book-outline.svg',
  }, {
    _id: 11,
    description: 'Mensalidade Facul',
    price: '700,00',
    category: 'Estudo',
    priority: 'Alta',
    iconUrl: '../static/img/icons/icon-book-outline.svg',
  }, {
    _id: 12,
    description: 'Novo Jordan',
    price: '60,41',
    category: 'Vestimenta',
    priority: 'Alta',
    iconUrl: '../static/img/icons/icon-shirt-outline.svg',
  }, {
    _id: 13,
    description: 'Conta de Luz',
    price: '82,67',
    category: 'Casa',
    priority: 'Alta',
    iconUrl: '../static/img/icons/icon-home-outline.svg',
  }, {
    _id: 14,
    description: 'Conta de Água',
    price: '70,00',
    category: 'Casa',
    priority: 'Alta',
    iconUrl: '../static/img/icons/icon-home-outline.svg',
  }, {
    _id: 15,
    description: 'Internet',
    price: '70,00',
    category: 'Casa',
    priority: 'Alta',
    iconUrl: '../static/img/icons/icon-home-outline.svg',
  }
]